tasks:
  - name: assign-to-project
    on:
      issues:
        types: [opened]
    condition: 'config.users.includes(payload.issue.user.login)'
    config:
      project-id: 2
      column-id: 12189604
      users: [elylucas]
