name: Bot

on:
  issues:
    types: [opened]

jobs:
  bot:
    name: ${{ github.event_name }}/${{ github.event.action }}
    runs-on: ubuntu-latest
    steps:
      - uses: ionic-team/bot@1f11dff2b9394de8149403e40411f02f700b9232
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}