name: Bot

on:
  issues:
    types: [opened]

jobs:
  bot:
    name: ${{ github.event_name }}/${{ github.event.action }}
    runs-on: ubuntu-latest
    steps:
      - uses: ionic-team/bot@ba262d
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}