name: Bot

on:
  issues:
    types: [opened]

jobs:
  bot:
    name: ${{ github.event_name }}/${{ github.event.action }}
    runs-on: ubuntu-latest
    steps:
      - uses: ionic-team/bot@76299ba2e0f24a01b1f6339be7bdd2d46f3c9ac2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}